### ISSUE TITLE
Some clearer build instructions

### ISSUE THREAD

**Issue by cjhanks** [Obi-Wan/dwt#1]
Unfortunately knowledge of `autotools` is becoming less common.  Adding this to the `INSTALL` might help.

```
$> libtoolize
$> aclocal
$> autoheader
$> automake --add-missing
$> autoconf
$> ./configure
$> make
```

**Comment by Obi-Wan** [comment]
Dear Christopher, I just pushed a fix for this. Thanks for pointing this out!
